import type {
  BackendEvent,
  CalendarEvent,
  CategoryKey,
  ExploreCard,
} from "./types";

export const HAARLEM_DUMMY_EVENTS: BackendEvent[] = [
  {
    id: 101,
    title: "Teylers Avondopenstelling",
    city: "haarlem",
    venue: "Teylers Museum",
    start_at: "2026-04-03T18:30:00",
    end_at: "2026-04-03T21:00:00",
    date_text: "Vrijdag 3 april",
    is_ongoing: false,
    is_free: false,
    price_min: 12.5,
    source_url: "#",
    latitude: 52.3809,
    longitude: 4.6366,
  },
  {
    id: 102,
    title: "Jazz aan het Spaarne",
    city: "haarlem",
    venue: "Philharmonie Haarlem",
    start_at: "2026-04-05T20:00:00",
    end_at: "2026-04-05T22:30:00",
    date_text: "Zondag 5 april",
    is_ongoing: false,
    is_free: false,
    price_min: 19,
    source_url: "#",
    latitude: 52.3815,
    longitude: 4.6372,
  },
  {
    id: 103,
    title: "Food Market Grote Markt",
    city: "haarlem",
    venue: "Grote Markt",
    start_at: "2026-04-06T12:00:00",
    end_at: "2026-04-06T18:00:00",
    date_text: "Maandag 6 april",
    is_ongoing: false,
    is_free: true,
    price_min: 0,
    source_url: "#",
    latitude: 52.3813,
    longitude: 4.636,
  },
  {
    id: 104,
    title: "Historische Hofjeswandeling",
    city: "haarlem",
    venue: "Centrum Haarlem",
    start_at: "2026-04-07T10:30:00",
    end_at: "2026-04-07T12:00:00",
    date_text: "Dinsdag 7 april",
    is_ongoing: false,
    is_free: false,
    price_min: 8.5,
    source_url: "#",
    latitude: 52.3797,
    longitude: 4.6328,
  },
  {
    id: 105,
    title: "Openlucht Filmavond",
    city: "haarlem",
    venue: "Haarlemmerhout",
    start_at: "2026-04-09T20:30:00",
    end_at: "2026-04-09T23:00:00",
    date_text: "Donderdag 9 april",
    is_ongoing: false,
    is_free: true,
    price_min: 0,
    source_url: "#",
    latitude: 52.3735,
    longitude: 4.6244,
  },
  {
    id: 106,
    title: "Lokale Makers Markt",
    city: "haarlem",
    venue: "Koepel Haarlem",
    start_at: "2026-04-10T11:00:00",
    end_at: "2026-04-10T17:00:00",
    date_text: "Vrijdag 10 april",
    is_ongoing: false,
    is_free: true,
    price_min: 0,
    source_url: "#",
    latitude: 52.3873,
    longitude: 4.6461,
  },
];

export const mockCardsByCategory: Record<CategoryKey, ExploreCard[]> = {
  events: [
    {
      id: 1,
      title: "Teylers Avondopenstelling",
      label: "MUSEUM EVENT",
      time: "18:30",
      location: "Teylers Museum",
      image: "/images/apeldoorn_img.jpg",
    },
    {
      id: 2,
      title: "Jazz aan het Spaarne",
      label: "LIVE MUZIEK",
      time: "20:00",
      location: "Philharmonie Haarlem",
      image: "/images/julianatoren.jpg",
    },
    {
      id: 3,
      title: "Food Market Grote Markt",
      label: "LOCAL EVENT",
      time: "12:00",
      location: "Grote Markt",
      image: "/images/apeldoorn_img.jpg",
    },
  ],
  attractions: [
    {
      id: 4,
      title: "Teylers Museum",
      label: "HIGHLIGHT",
      time: "Hele dag",
      location: "Centrum",
      image: "/images/apeldoorn_img.jpg",
    },
    {
      id: 5,
      title: "Molen de Adriaan",
      label: "CULTURE",
      time: "11:00",
      location: "Spaarne",
      image: "/images/julianatoren.jpg",
    },
    {
      id: 6,
      title: "Grote Markt",
      label: "CITY ICON",
      time: "Sunset",
      location: "Binnenstad",
      image: "/images/apeldoorn_img.jpg",
    },
  ],
  restaurants: [
    {
      id: 7,
      title: "Spaarne Bistro",
      label: "RESTAURANT",
      time: "Lunch & Diner",
      location: "Aan het water",
      image: "/images/apeldoorn_img.jpg",
    },
    {
      id: 8,
      title: "De Oude Stadskeuken",
      label: "LOCAL FAVORITE",
      time: "18:00",
      location: "Binnenstad",
      image: "/images/julianatoren.jpg",
    },
    {
      id: 9,
      title: "Morning Roast Haarlem",
      label: "COFFEE",
      time: "08:00",
      location: "Stationsbuurt",
      image: "/images/apeldoorn_img.jpg",
    },
  ],
  bars: [
    {
      id: 10,
      title: "Spaarne Social Club",
      label: "COCKTAILS",
      time: "21:00",
      location: "Centrum",
      image: "/images/apeldoorn_img.jpg",
    },
    {
      id: 11,
      title: "De Markt Pub",
      label: "PUB",
      time: "19:00",
      location: "Grote Markt",
      image: "/images/julianatoren.jpg",
    },
    {
      id: 12,
      title: "Rooftop Haarlem",
      label: "NIGHTLIFE",
      time: "22:00",
      location: "Binnenstad",
      image: "/images/apeldoorn_img.jpg",
    },
  ],
  thingsToDo: [
    {
      id: 13,
      title: "Hofjeswandeling",
      label: "OUTDOOR",
      time: "Middag",
      location: "Oude stad",
      image: "/images/apeldoorn_img.jpg",
    },
    {
      id: 14,
      title: "Keramiek Workshop",
      label: "EXPERIENCE",
      time: "13:00",
      location: "Creatief atelier",
      image: "/images/julianatoren.jpg",
    },
    {
      id: 15,
      title: "Lokale Markt Route",
      label: "LOCAL TIP",
      time: "Ochtend",
      location: "Centrum",
      image: "/images/apeldoorn_img.jpg",
    },
  ],
};

export const MONTH_NAMES = [
  "Januari",
  "Februari",
  "Maart",
  "April",
  "Mei",
  "Juni",
  "Juli",
  "Augustus",
  "September",
  "Oktober",
  "November",
  "December",
];

export const WEEKDAY_NAMES = ["MA", "DI", "WO", "DO", "VR", "ZA", "ZO"];

export const HAARLEM_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 1,
    title: "Fototentoonstelling aan het Spaarne",
    category: "Kunst",
    city: "Haarlem",
    date: "2026-04-03",
    time: "14:00",
    color: "green",
  },
  {
    id: 2,
    title: "Jazz in de Philharmonie",
    category: "Muziek",
    city: "Haarlem",
    date: "2026-04-05",
    time: "20:30",
    color: "purple",
  },
  {
    id: 3,
    title: "Voorjaarsconcert in de Bavokerk",
    category: "Muziek",
    city: "Haarlem",
    date: "2026-04-09",
    time: "19:30",
    color: "green",
  },
  {
    id: 4,
    title: "Street Food op de Grote Markt",
    category: "Culinair",
    city: "Haarlem",
    date: "2026-04-06",
    time: "18:00",
    color: "sand",
  },
  {
    id: 5,
    title: "Theateravond in de Schuur",
    category: "Theater",
    city: "Haarlem",
    date: "2026-04-12",
    time: "20:00",
    color: "purple",
  },
  {
    id: 6,
    title: "Kunstmarkt in de Koepel",
    category: "Kunst",
    city: "Haarlem",
    date: "2026-04-18",
    time: "11:00",
    color: "sand",
  },
];