import type {
  BackendEvent,
  CalendarEvent,
  CategoryKey,
  EditorialContent,
  ExploreCard,
} from "./types";

export const CITY_EDITORIAL_CONTENT: Record<string, EditorialContent> = {
  haarlem: {
    editionTag: "HAARLEM EDITION",
    titleIntro: "Ontdek de",
    titleAccent: "verborgen",
    titleOutro: "parels van Haarlem.",
    intro:
      "Van historische musea tot moderne jazz-avonden aan het water. Wij cureren de meest authentieke ervaringen in de stad van de bloemen.",
    ctaLabel: "Plan mijn moment",
    recommendations: [
      {
        id: 1,
        tag: "Populair",
        title: "Beste van vanavond",
        subtitle: "Foodhall in centrum",
        href: "#curated-picks",
      },
      {
        id: 2,
        tag: "Gratis",
        title: "Gratis favoriet",
        subtitle: "Stadswandeling Hofjes",
        href: "#curated-picks",
      },
      {
        id: 3,
        tag: "Dichtbij",
        title: "Binnen 15 min bereikbaar",
        subtitle: "Live muziek en jazz cafe",
        href: "#curated-picks",
      },
    ],
    momentFilters: ["Nu bezig", "Vanavond", "Morgen", "Dit weekend"],
    featureCards: [
      {
        id: 1,
        title: "Expert Curation",
        description:
          "Elke plek is handmatig geselecteerd door curators die Haarlem kennen van hofje tot kade.",
        icon: "spark",
        tone: "butter",
      },
      {
        id: 2,
        title: "Real-time Updates",
        description:
          "Openingsuren, last-minute events en tijdelijke exposities worden direct bijgewerkt in je selectie.",
        icon: "clock",
        tone: "mint",
      },
      {
        id: 3,
        title: "Smart Routes",
        description:
          "Plan je dag rond logische looplijnen zodat je meer ziet en minder tijd verliest tussen stops.",
        icon: "map",
        tone: "mist",
      },
    ],
  },
  apeldoorn: {
    editionTag: "APELDOORN EDITION",
    titleIntro: "Vind de",
    titleAccent: "frisse",
    titleOutro: "momenten van Apeldoorn.",
    intro:
      "Van creatieve avonden tot groene stadsroutes. We combineren cultuur, ontspanning en lokale adressen in een route die direct werkt.",
    ctaLabel: "Plan mijn moment",
    recommendations: [
      {
        id: 1,
        tag: "Vanavond",
        title: "Avond vol sfeer",
        subtitle: "Museum plus live muziek",
        href: "#curated-picks",
      },
      {
        id: 2,
        tag: "Buiten",
        title: "Groene favoriet",
        subtitle: "Wandeling door Berg en Bos",
        href: "#curated-picks",
      },
      {
        id: 3,
        tag: "Centrum",
        title: "Snel bereikbaar",
        subtitle: "Culinair en cultuur op loopafstand",
        href: "#curated-picks",
      },
    ],
    momentFilters: ["Nu bezig", "Vanavond", "Morgen", "Weekend"],
    featureCards: [
      {
        id: 1,
        title: "Lokale selectie",
        description:
          "Samengesteld voor een spontane middag of avond in de stad, zonder eindeloos zoeken.",
        icon: "spark",
        tone: "butter",
      },
      {
        id: 2,
        title: "Live planning",
        description:
          "Je ziet meteen welke stops nog haalbaar zijn op basis van tijd, afstand en sfeer.",
        icon: "clock",
        tone: "mint",
      },
      {
        id: 3,
        title: "Slim combineren",
        description:
          "Cultuur, horeca en buitenplekken worden gecombineerd tot routes die echt prettig aanvoelen.",
        icon: "map",
        tone: "mist",
      },
    ],
  },
  default: {
    editionTag: "CITY EDITION",
    titleIntro: "Ontdek de",
    titleAccent: "curated",
    titleOutro: "plekken van deze stad.",
    intro:
      "Van culturele stops tot lokale favorieten. Wij zetten de momenten klaar die een dag in de stad net wat rijker maken.",
    ctaLabel: "Plan mijn moment",
    recommendations: [
      {
        id: 1,
        tag: "Aanrader",
        title: "Snel startpunt",
        subtitle: "Een mix van cultuur en horeca",
        href: "#curated-picks",
      },
      {
        id: 2,
        tag: "Gratis",
        title: "Laagdrempelige tip",
        subtitle: "Perfect voor een spontane stop",
        href: "#curated-picks",
      },
      {
        id: 3,
        tag: "Route",
        title: "Slim te combineren",
        subtitle: "Kies plekken die dicht bij elkaar liggen",
        href: "#curated-picks",
      },
    ],
    momentFilters: ["Nu bezig", "Later", "Morgen", "Weekend"],
    featureCards: [
      {
        id: 1,
        title: "Carefully Curated",
        description:
          "Een heldere selectie van plekken die de sfeer van de stad voelbaar maken.",
        icon: "spark",
        tone: "butter",
      },
      {
        id: 2,
        title: "Up-to-date",
        description:
          "Momenten en adressen blijven bruikbaar doordat we ze regelmatig verversen.",
        icon: "clock",
        tone: "mint",
      },
      {
        id: 3,
        title: "Easy Routes",
        description:
          "Combineer stops die logisch op elkaar volgen voor een fijnere stadsdag.",
        icon: "map",
        tone: "mist",
      },
    ],
  },
};

export const HAARLEM_DUMMY_EVENTS: BackendEvent[] = [
  {
    id: 101,
    title: "Teylers Avondopenstelling",
    city: "haarlem",
    venue: "Teylers Museum",
    start_at: "2026-04-10T19:00:00",
    end_at: "2026-04-10T22:00:00",
    date_text: "Vrijdag 10 april",
    is_ongoing: false,
    is_free: false,
    price_min: 15,
    source_url: "#",
    latitude: 52.3809,
    longitude: 4.6366,
    summary:
      "Beleef het oudste museum van Nederland in een magisch avondlicht met rustiger publiek.",
    walk_minutes: 8,
    rating: 4.9,
    image: "/images/apeldoorn_img.jpg",
    status: "Nu open",
    category_label: "Museum avond",
    audiences: ["solo", "date", "vrienden"],
    moments: ["nu", "vanavond"],
    vibes: ["cultureel", "relaxed"],
  },
  {
    id: 102,
    title: "Jazz aan het Spaarne",
    city: "haarlem",
    venue: "Spaarne Kade",
    start_at: "2026-04-10T20:30:00",
    end_at: "2026-04-10T23:00:00",
    date_text: "Vrijdag 10 april",
    is_ongoing: false,
    is_free: true,
    price_min: 0,
    source_url: "#",
    latitude: 52.3815,
    longitude: 4.6372,
    summary:
      "Live jazz met uitzicht op het water en genoeg ruimte om nog aan te schuiven voor een spontane avond.",
    walk_minutes: 12,
    rating: 4.7,
    image: "/images/apeldoorn_img.jpg",
    status: "Start over 30 min",
    category_label: "Live muziek",
    audiences: ["date", "vrienden"],
    moments: ["vanavond"],
    vibes: ["eten-drinken", "relaxed"],
  },
  {
    id: 103,
    title: "Food Market Grote Markt",
    city: "haarlem",
    venue: "Grote Markt",
    start_at: "2026-04-11T12:00:00",
    end_at: "2026-04-11T18:00:00",
    date_text: "Zaterdag 11 april",
    is_ongoing: false,
    is_free: true,
    price_min: 0,
    source_url: "#",
    latitude: 52.3813,
    longitude: 4.636,
    summary:
      "Een energieke mix van lokale makers, streetfood en zonnige terrassen op het hart van de stad.",
    walk_minutes: 6,
    rating: 4.8,
    image: "/images/apeldoorn_img.jpg",
    status: "Morgen vanaf 12:00",
    category_label: "Culinair",
    audiences: ["date", "gezin", "vrienden"],
    moments: ["morgen", "weekend"],
    vibes: ["eten-drinken", "relaxed"],
  },
  {
    id: 104,
    title: "Historische Hofjeswandeling",
    city: "haarlem",
    venue: "Verzamelen op de Grote Houtstraat",
    start_at: "2026-04-11T10:30:00",
    end_at: "2026-04-11T12:00:00",
    date_text: "Zaterdag 11 april",
    is_ongoing: false,
    is_free: false,
    price_min: 8.5,
    source_url: "#",
    latitude: 52.3797,
    longitude: 4.6328,
    summary:
      "Wandel langs de stille binnentuinen en hoor de verhalen die Haarlem zijn zachte karakter geven.",
    walk_minutes: 10,
    rating: 4.8,
    image: "/images/apeldoorn_img.jpg",
    status: "Morgen ochtend",
    category_label: "Stadswandeling",
    audiences: ["solo", "date", "gezin"],
    moments: ["morgen", "weekend"],
    vibes: ["cultureel", "actief"],
  },
  {
    id: 105,
    title: "Openlucht Filmavond",
    city: "haarlem",
    venue: "Haarlemmerhout",
    start_at: "2026-04-11T21:00:00",
    end_at: "2026-04-11T23:30:00",
    date_text: "Zaterdag 11 april",
    is_ongoing: false,
    is_free: true,
    price_min: 0,
    source_url: "#",
    latitude: 52.3735,
    longitude: 4.6244,
    summary:
      "Films onder de bomen, dekens in het gras en precies genoeg levendigheid voor een zachte zaterdagavond.",
    walk_minutes: 18,
    rating: 4.6,
    image: "/images/apeldoorn_img.jpg",
    status: "Morgen avond",
    category_label: "Buiten",
    audiences: ["date", "vrienden"],
    moments: ["morgen", "weekend"],
    vibes: ["relaxed", "actief"],
  },
  {
    id: 106,
    title: "Lokale Makers Markt",
    city: "haarlem",
    venue: "Koepel Haarlem",
    start_at: "2026-04-12T11:00:00",
    end_at: "2026-04-12T17:00:00",
    date_text: "Zondag 12 april",
    is_ongoing: false,
    is_free: true,
    price_min: 0,
    source_url: "#",
    latitude: 52.3873,
    longitude: 4.6461,
    summary:
      "Keramiek, prints en kleine labels in een monumentale setting die steeds weer verrassend voelt.",
    walk_minutes: 15,
    rating: 4.5,
    image: "/images/apeldoorn_img.jpg",
    status: "Zondag favoriet",
    category_label: "Design markt",
    audiences: ["solo", "date", "vrienden"],
    moments: ["weekend"],
    vibes: ["cultureel", "eten-drinken"],
  },
];

export const APELDOORN_DUMMY_EVENTS: BackendEvent[] = [
  {
    id: 201,
    title: "Avond in CODA Museum",
    city: "apeldoorn",
    venue: "CODA Museum",
    start_at: "2026-04-10T19:00:00",
    end_at: "2026-04-10T21:30:00",
    date_text: "Vrijdag 10 april",
    is_ongoing: false,
    is_free: false,
    price_min: 14.5,
    source_url: "#",
    latitude: 52.2136,
    longitude: 5.9595,
    summary:
      "Een rustige culturele avond met design, licht en genoeg tijd voor een drankje erna.",
    walk_minutes: 7,
    rating: 4.7,
    image: "/images/apeldoorn_img.jpg",
    status: "Vanavond",
    category_label: "Museum avond",
    audiences: ["solo", "date"],
    moments: ["vanavond"],
    vibes: ["cultureel", "relaxed"],
  },
  {
    id: 202,
    title: "Live muziek in Gigant",
    city: "apeldoorn",
    venue: "Gigant",
    start_at: "2026-04-10T20:30:00",
    end_at: "2026-04-10T23:00:00",
    date_text: "Vrijdag 10 april",
    is_ongoing: false,
    is_free: false,
    price_min: 18,
    source_url: "#",
    latitude: 52.2148,
    longitude: 5.9631,
    summary:
      "Een stevige live-set in een zaal waar je makkelijk een spontane avond van maakt.",
    walk_minutes: 9,
    rating: 4.6,
    image: "/images/julianatoren.jpg",
    status: "Start om 20:30",
    category_label: "Live muziek",
    audiences: ["date", "vrienden"],
    moments: ["vanavond"],
    vibes: ["eten-drinken", "relaxed"],
  },
  {
    id: 203,
    title: "Food & Drinks op het Marktplein",
    city: "apeldoorn",
    venue: "Marktplein",
    start_at: "2026-04-11T12:00:00",
    end_at: "2026-04-11T18:00:00",
    date_text: "Zaterdag 11 april",
    is_ongoing: false,
    is_free: true,
    price_min: 0,
    source_url: "#",
    latitude: 52.2119,
    longitude: 5.9692,
    summary:
      "Streetfood, picknicktafels en een levendige zaterdagmiddag in het centrum.",
    walk_minutes: 5,
    rating: 4.6,
    image: "/images/apeldoorn_img.jpg",
    status: "Morgen vanaf 12:00",
    category_label: "Culinair",
    audiences: ["date", "gezin", "vrienden"],
    moments: ["morgen", "weekend"],
    vibes: ["eten-drinken", "relaxed"],
  },
  {
    id: 204,
    title: "Wandeling door Park Berg & Bos",
    city: "apeldoorn",
    venue: "Park Berg & Bos",
    start_at: "2026-04-11T10:00:00",
    end_at: "2026-04-11T12:30:00",
    date_text: "Zaterdag 11 april",
    is_ongoing: false,
    is_free: false,
    price_min: 7.5,
    source_url: "#",
    latitude: 52.225,
    longitude: 5.9338,
    summary:
      "Een groene route voor wie stad en natuur in een middag wil combineren.",
    walk_minutes: 16,
    rating: 4.8,
    image: "/images/apeldoorn_img.jpg",
    status: "Morgen ochtend",
    category_label: "Buiten",
    audiences: ["solo", "gezin", "vrienden"],
    moments: ["morgen", "weekend"],
    vibes: ["actief", "relaxed"],
  },
  {
    id: 205,
    title: "Filmavond in Vue Apeldoorn",
    city: "apeldoorn",
    venue: "Vue Apeldoorn",
    start_at: "2026-04-11T20:15:00",
    end_at: "2026-04-11T22:45:00",
    date_text: "Zaterdag 11 april",
    is_ongoing: false,
    is_free: false,
    price_min: 11,
    source_url: "#",
    latitude: 52.219,
    longitude: 5.9674,
    summary:
      "Een makkelijke avondstop als je iets wilt doen zonder veel planning vooraf.",
    walk_minutes: 11,
    rating: 4.5,
    image: "/images/julianatoren.jpg",
    status: "Morgen avond",
    category_label: "Film",
    audiences: ["date", "vrienden"],
    moments: ["morgen", "weekend"],
    vibes: ["relaxed", "eten-drinken"],
  },
  {
    id: 206,
    title: "Voorjaarsmarkt in het centrum",
    city: "apeldoorn",
    venue: "Binnenstad Apeldoorn",
    start_at: "2026-04-12T11:00:00",
    end_at: "2026-04-12T17:00:00",
    date_text: "Zondag 12 april",
    is_ongoing: false,
    is_free: true,
    price_min: 0,
    source_url: "#",
    latitude: 52.2133,
    longitude: 5.9601,
    summary:
      "Lokale ondernemers, eerste terraszon en genoeg stops om je dag rustig op te bouwen.",
    walk_minutes: 6,
    rating: 4.4,
    image: "/images/apeldoorn_img.jpg",
    status: "Zondag favoriet",
    category_label: "Markt",
    audiences: ["gezin", "vrienden"],
    moments: ["weekend"],
    vibes: ["eten-drinken", "relaxed"],
  },
];

export const mockCardsByCategory: Record<CategoryKey, ExploreCard[]> = {
  events: [
    {
      id: 1,
      title: "Teylers Avondopenstelling",
      label: "Museum avond",
      time: "19:00 - 22:00",
      location: "Teylers Museum",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/teylers-avondopenstelling",
      description:
        "Beleef het oudste museum van Nederland in een rustiger avondsetting.",
      price: "EUR 15,00",
      distance: "8 min lopen",
      status: "Nu open",
      rating: 4.9,
      audiences: ["solo", "date", "vrienden"],
      moments: ["nu", "vanavond"],
      vibes: ["cultureel", "relaxed"],
    },
    {
      id: 2,
      title: "Jazz aan het Spaarne",
      label: "Live muziek",
      time: "20:30 - 23:00",
      location: "Spaarne Kade",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/jazz-aan-het-spaarne",
      description:
        "Een losse jazzavond aan het water met genoeg ruimte voor spontane plannen.",
      price: "Gratis",
      distance: "12 min lopen",
      status: "Start over 30 min",
      rating: 4.7,
      audiences: ["date", "vrienden"],
      moments: ["vanavond"],
      vibes: ["eten-drinken", "relaxed"],
    },
    {
      id: 3,
      title: "Food Market Grote Markt",
      label: "Culinair",
      time: "12:00 - 18:00",
      location: "Grote Markt",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/food-market-grote-markt",
      description:
        "Lokale smaken, kleine makers en een zonnig stadsgevoel in een middag.",
      price: "Gratis",
      distance: "6 min lopen",
      status: "Morgen vanaf 12:00",
      rating: 4.8,
      audiences: ["date", "gezin", "vrienden"],
      moments: ["morgen", "weekend"],
      vibes: ["eten-drinken", "relaxed"],
    },
  ],
  attractions: [
    {
      id: 4,
      title: "Teylers Museum",
      label: "Highlight",
      time: "10:00 - 17:00",
      location: "Centrum",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/teylers-museum",
      description:
        "Een klassieke eerste stop als je kunst, wetenschap en stille grandeur wilt combineren.",
      price: "EUR 16,00",
      distance: "7 min lopen",
      status: "Vandaag open",
      rating: 4.8,
      audiences: ["solo", "date", "gezin"],
      moments: ["nu", "morgen", "weekend"],
      vibes: ["cultureel", "relaxed"],
    },
    {
      id: 5,
      title: "Molen De Adriaan",
      label: "Culture",
      time: "11:00 - 17:00",
      location: "Spaarne",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/molen-de-adriaan",
      description:
        "Een iconisch uitzichtpunt dat Haarlem meteen herkenbaar en tastbaar maakt.",
      price: "EUR 7,50",
      distance: "15 min lopen",
      status: "Nu open",
      rating: 4.6,
      audiences: ["solo", "date", "vrienden"],
      moments: ["nu", "morgen", "weekend"],
      vibes: ["cultureel", "actief"],
    },
    {
      id: 6,
      title: "Grote Markt",
      label: "City icon",
      time: "Hele dag",
      location: "Binnenstad",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/grote-markt-haarlem",
      description:
        "Het plein waar terrassen, monumenten en stadsleven het makkelijkst samenkomen.",
      price: "Gratis",
      distance: "5 min lopen",
      status: "Altijd dichtbij",
      rating: 4.7,
      audiences: ["date", "gezin", "vrienden"],
      moments: ["nu", "morgen", "weekend"],
      vibes: ["cultureel", "eten-drinken"],
    },
  ],
  restaurants: [
    {
      id: 7,
      title: "Spaarne Bistro",
      label: "Restaurant",
      time: "Lunch en diner",
      location: "Aan het water",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/spaarne-bistro",
      description:
        "Intiem dineren aan het water met een kaart die seizoensproducten centraal zet.",
      price: "EUR 18 - EUR 36",
      distance: "9 min lopen",
      status: "Vanavond plek",
      rating: 4.7,
      audiences: ["date", "vrienden"],
      moments: ["vanavond", "morgen", "weekend"],
      vibes: ["eten-drinken", "relaxed"],
    },
    {
      id: 8,
      title: "De Oude Stadskeuken",
      label: "Local favorite",
      time: "18:00 - laat",
      location: "Binnenstad",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/de-oude-stadskeuken",
      description:
        "Een warm adres voor wie een klassieke stadsavond zoekt zonder teveel poespas.",
      price: "EUR 22 - EUR 40",
      distance: "8 min lopen",
      status: "Reserveer op tijd",
      rating: 4.8,
      audiences: ["date", "vrienden"],
      moments: ["vanavond", "morgen", "weekend"],
      vibes: ["eten-drinken", "relaxed"],
    },
    {
      id: 9,
      title: "Morning Roast Haarlem",
      label: "Coffee",
      time: "08:00 - 16:00",
      location: "Stationsbuurt",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/morning-roast-haarlem",
      description:
        "Goede koffie, rustige tafels en een fijne eerste stop voordat je de stad in trekt.",
      price: "EUR 4 - EUR 14",
      distance: "11 min lopen",
      status: "Vanaf 08:00",
      rating: 4.5,
      audiences: ["solo", "date"],
      moments: ["nu", "morgen", "weekend"],
      vibes: ["eten-drinken", "relaxed"],
    },
  ],
  bars: [
    {
      id: 10,
      title: "Spaarne Social Club",
      label: "Cocktails",
      time: "21:00 - laat",
      location: "Centrum",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/spaarne-social-club",
      description:
        "Een levendige avondplek met nette cocktails en genoeg energie voor een late stop.",
      price: "EUR 11 per cocktail",
      distance: "10 min lopen",
      status: "Vanavond sfeervol",
      rating: 4.6,
      audiences: ["date", "vrienden"],
      moments: ["vanavond", "weekend"],
      vibes: ["eten-drinken", "relaxed"],
    },
    {
      id: 11,
      title: "De Markt Pub",
      label: "Pub",
      time: "19:00 - laat",
      location: "Grote Markt",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/de-markt-pub",
      description:
        "Voor een lossere avond met vrienden, speciaalbier en uitzicht op het plein.",
      price: "EUR 5 - EUR 9",
      distance: "5 min lopen",
      status: "Nu levendig",
      rating: 4.4,
      audiences: ["vrienden"],
      moments: ["nu", "vanavond", "weekend"],
      vibes: ["eten-drinken", "actief"],
    },
    {
      id: 12,
      title: "Rooftop Haarlem",
      label: "Nightlife",
      time: "22:00 - laat",
      location: "Binnenstad",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/rooftop-haarlem",
      description:
        "Een hoger gelegen avondstop met panoramisch zicht en een iets uitgesprokener sfeer.",
      price: "EUR 12 - EUR 16",
      distance: "14 min lopen",
      status: "Na 22:00 op zijn best",
      rating: 4.5,
      audiences: ["date", "vrienden"],
      moments: ["vanavond", "weekend"],
      vibes: ["eten-drinken", "relaxed"],
    },
  ],
  thingsToDo: [
    {
      id: 13,
      title: "Hofjeswandeling",
      label: "Outdoor",
      time: "Middag",
      location: "Oude stad",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/hofjeswandeling",
      description:
        "Een stille route langs binnentuinen en verborgen doorgangen voor een langzamere stadsdag.",
      price: "EUR 8,50",
      distance: "10 min lopen",
      status: "Morgen middag",
      rating: 4.8,
      audiences: ["solo", "date", "gezin"],
      moments: ["morgen", "weekend"],
      vibes: ["cultureel", "actief"],
    },
    {
      id: 14,
      title: "Keramiek Workshop",
      label: "Experience",
      time: "13:00 - 15:00",
      location: "Creatief atelier",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/keramiek-workshop",
      description:
        "Een compacte workshop die goed werkt als creatieve onderbreking van een stadsroute.",
      price: "EUR 24,50",
      distance: "13 min lopen",
      status: "Nog plekken",
      rating: 4.6,
      audiences: ["solo", "date", "vrienden"],
      moments: ["morgen", "weekend"],
      vibes: ["cultureel", "actief"],
    },
    {
      id: 15,
      title: "Lokale Markt Route",
      label: "Local tip",
      time: "Ochtend",
      location: "Centrum",
      image: "/images/apeldoorn_img.jpg",
      href: "/ontdek/lokale-markt-route",
      description:
        "Een combinatie van vaste adressen en tijdelijke kraampjes voor een levendige ochtend.",
      price: "Gratis",
      distance: "6 min lopen",
      status: "Beste in de ochtend",
      rating: 4.5,
      audiences: ["solo", "gezin", "vrienden"],
      moments: ["nu", "morgen", "weekend"],
      vibes: ["eten-drinken", "relaxed"],
    },
  ],
};

export const MONTH_NAMES = [
  "Januari",
  "Februari",
  "Maart",
  "April",
  "Mei",
  "Juni",
  "Juli",
  "Augustus",
  "September",
  "Oktober",
  "November",
  "December",
];

export const WEEKDAY_NAMES = ["MA", "DI", "WO", "DO", "VR", "ZA", "ZO"];

export const HAARLEM_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 1,
    title: "Fototentoonstelling aan het Spaarne",
    category: "Kunst",
    city: "Haarlem",
    date: "2026-04-03",
    time: "14:00",
    color: "green",
  },
  {
    id: 2,
    title: "Jazz in de Philharmonie",
    category: "Muziek",
    city: "Haarlem",
    date: "2026-04-05",
    time: "20:30",
    color: "purple",
  },
  {
    id: 3,
    title: "Voorjaarsconcert in de Bavokerk",
    category: "Muziek",
    city: "Haarlem",
    date: "2026-04-09",
    time: "19:30",
    color: "green",
  },
  {
    id: 4,
    title: "Street Food op de Grote Markt",
    category: "Culinair",
    city: "Haarlem",
    date: "2026-04-06",
    time: "18:00",
    color: "sand",
  },
  {
    id: 5,
    title: "Theateravond in de Schuur",
    category: "Theater",
    city: "Haarlem",
    date: "2026-04-12",
    time: "20:00",
    color: "purple",
  },
  {
    id: 6,
    title: "Kunstmarkt in de Koepel",
    category: "Kunst",
    city: "Haarlem",
    date: "2026-04-18",
    time: "11:00",
    color: "sand",
  },
];
