import type { Metadata } from "next";
import { notFound } from "next/navigation";

import Breadcrumbs from "@/components/Breadcrumbs";
import FavouriteButton from "@/components/FavouriteButton";
import { buildActionSearchHref, buildMapsSearchHref } from "@/lib/actionLinks";
import { getCityContentBySlug } from "@/lib/api/cityContent";
import { normalizeCitySlug } from "@/lib/cityConfig";
import { getAllExploreDetailSlugs, getExploreDetailBySlug, getFallbackExploreTitle, mapCityContentToExploreDetail } from "@/lib/exploreDetailData";
import { optimizeCssBackground } from "@/lib/remoteImage";

type PageProps = { params: { slug: string }; searchParams?: { city?: string } };
export const dynamicParams = true;
export const runtime = "edge";
export function generateStaticParams() { return getAllExploreDetailSlugs().map((slug) => ({ slug })); }

function cleanText(value?: string | null) { const clean = value?.trim(); return clean && !["undefined", "null", "nan"].includes(clean.toLowerCase()) ? clean : null; }
async function getExploreDetail(slug: string) {
  const fallback = getExploreDetailBySlug(slug);
  if (fallback) return fallback;
  const cityItem = await getCityContentBySlug(slug);
  return cityItem ? mapCityContentToExploreDetail(cityItem, slug) : null;
}
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  try {
    const item = await getExploreDetail(params.slug);
    if (!item) return { title: "Uitje niet gevonden | Uitjes", description: "Ontdek andere activiteiten en plekken in Nederland." };
    const title = cleanText(item.title) || getFallbackExploreTitle(params.slug);
    const city = cleanText(item.city) || "Nederland";
    return { title: `${title} in ${city} | Uitjes`, description: cleanText(item.description) || cleanText(item.aboutText) || `${title} is een uitje in ${city}.`, alternates: { canonical: `/ontdek/${encodeURIComponent(params.slug)}` } };
  } catch {
    return { title: `${getFallbackExploreTitle(params.slug)} | Uitjes`, description: "Bekijk dit uitje en ontdek meer activiteiten in Nederland." };
  }
}

function ArrowIcon() { return <svg className="h-4 w-4" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M3.333 8h9.334M8.667 3.333 13.333 8l-4.666 4.667" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function PinIcon() { return <svg className="h-4 w-4" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M8 14s4-3.6 4-7.333A4 4 0 1 0 4 6.667C4 10.4 8 14 8 14Z" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" /><circle cx="8" cy="6.667" r="1.4" fill="currentColor" /></svg>; }
function TicketIcon() { return <svg className="h-4 w-4" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M2.5 5.25a1.75 1.75 0 0 0 1.75-1.75h7.5A1.75 1.75 0 0 0 13.5 5.25v1A1.75 1.75 0 0 0 11.75 8a1.75 1.75 0 0 0 1.75 1.75v1A1.75 1.75 0 0 0 11.75 12.5h-7.5A1.75 1.75 0 0 0 2.5 10.75v-1A1.75 1.75 0 0 0 4.25 8 1.75 1.75 0 0 0 2.5 6.25v-1Z" stroke="currentColor" strokeWidth="1.3" strokeLinejoin="round" /></svg>; }
function SparkIcon() { return <svg className="h-5 w-5" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m10 2 1.48 5.1L16.5 8.5l-5.02 1.4L10 15l-1.48-5.1L3.5 8.5l5.02-1.4L10 2Z" stroke="currentColor" strokeWidth="1.35" strokeLinejoin="round" /></svg>; }
function ImageSurface({ image, className, children }: { image?: string | null; className: string; children?: React.ReactNode }) { return <div className={className} style={image ? { backgroundImage: `linear-gradient(180deg, rgba(25,45,33,0.02), rgba(25,45,33,0.24)), ${optimizeCssBackground(image, { width: 1400, quality: 68 })}`, backgroundSize: "cover", backgroundPosition: "center" } : undefined}>{children}</div>; }
function InfoGroup({ title, rows }: { title: string; rows: Array<[string, string | null | undefined]> }) { const valid = rows.filter((row): row is [string, string] => Boolean(row[1])); if (!valid.length) return null; return <details open className="group overflow-hidden rounded-[1.05rem] border border-[#dce1d9] bg-[#fdfdf9] [&_summary::-webkit-details-marker]:hidden"><summary className="flex min-h-[4.5rem] cursor-pointer list-none items-center justify-between gap-4 px-5 text-[1.02rem] font-semibold tracking-[-0.025em] text-[#25382e]"><span>{title}</span><svg className="h-4 w-4 text-[#59685d] transition group-open:rotate-180" viewBox="0 0 16 16" fill="none"><path d="m4 9.5 4-4 4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg></summary><dl className="border-t border-[#e2e5df]">{valid.map(([label, value]) => <div key={label} className="grid gap-1 border-b border-[#e2e5df] px-5 py-3.5 last:border-0 sm:grid-cols-[9rem_1fr] sm:gap-6"><dt className="text-sm text-[#70776f]">{label}</dt><dd className="text-sm font-semibold leading-6 text-[#25382e]">{value}</dd></div>)}</dl></details>; }

export default async function ExploreDetailPage({ params, searchParams }: PageProps) {
  const item = await getExploreDetail(params.slug);
  if (!item) notFound();
  const citySlug = normalizeCitySlug(searchParams?.city || item.citySlug || item.city);
  const exploreBackHref = citySlug ? `/ontdek?city=${encodeURIComponent(citySlug)}` : "/ontdek";
  const locationQuery = [item.practical.venue, item.practical.address, item.city].filter(Boolean).join(", ");
  const routeHref = locationQuery ? buildMapsSearchHref(locationQuery) : null;
  const reserveHref = item.links?.ticketUrl || item.links?.reservationUrl || item.links?.sourceUrl || buildActionSearchHref({ title: item.title, location: locationQuery, actionLabel: item.actions.reserveLabel });
  const heroImage = item.heroImage || item.gallery[0];
  const practicalRows: Array<[string, string | null | undefined]> = [["Locatie", item.practical.venue || item.practical.address], ["Stad", item.city], ["Datum en tijd", item.practical.openingHours], ["Prijs", item.practical.pricing], ["Type", item.practical.cuisine || item.kind]];
  const visitRows: Array<[string, string | null | undefined]> = [["Praktische info", item.practical.practicalInfo], ["Status", item.status], ["Categorie", item.category], ["Tags", item.tags?.join(" · ")]];

  return <main className="min-h-screen bg-[#fbfaf6] text-[#203329]"><div className="mx-auto max-w-[1420px] px-4 pb-20 pt-5 sm:px-6 sm:pt-8 lg:px-10 lg:pb-28">
    <Breadcrumbs className="mb-7 sm:mb-9" items={[{ label: "Home", href: "/" }, { label: "Ontdek", href: exploreBackHref }, { label: item.title }]} />
    <section className="overflow-hidden rounded-[1.75rem] bg-[#eff0eb] shadow-[0_24px_70px_rgba(33,49,40,0.08)] lg:grid lg:grid-cols-[minmax(0,0.88fr)_minmax(0,1.12fr)]" aria-labelledby="explore-title"><div className="relative z-10 min-w-0 overflow-hidden px-6 py-8 sm:px-10 sm:py-11 lg:px-14 lg:py-14"><div className="absolute left-0 top-0 h-24 w-24 rounded-br-[5rem] border-b border-r border-[#dae4d7]" aria-hidden="true" /><div className="relative"><div className="flex flex-wrap items-center gap-2"></div><h1 id="explore-title" className="mt-8 max-w-[10ch] break-words text-[clamp(3.25rem,6.2vw,6.4rem)] font-semibold leading-[0.88] tracking-[-0.072em] text-[#15251d] [overflow-wrap:anywhere]">{item.title}</h1><p className="mt-6 max-w-xl text-[1rem] leading-7 text-[#5f6d63] sm:text-[1.08rem]">{item.subtitle || item.description || item.aboutText}</p><div className="mt-8 grid max-w-xl gap-3 border-y border-[#d8dfd5] py-5 text-sm text-[#365045] sm:grid-cols-2"><span className="inline-flex items-center gap-2.5"><PinIcon />{item.city}</span><span className="inline-flex items-center gap-2.5"><TicketIcon />{item.practical.pricing || "Bekijk actuele prijs"}</span><span className="inline-flex items-center gap-2.5 sm:col-span-2"><PinIcon />{item.practical.venue || item.practical.address || "Locatie volgt"}</span></div><div className="mt-8 flex flex-wrap gap-3"><a href={reserveHref} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#203d2e] px-5 text-sm font-semibold text-white transition hover:bg-[#315b43]"><TicketIcon /> {item.actions.reserveLabel || "Bekijk opties"}</a>{routeHref ? <a href={routeHref} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-[#c8d3c7] bg-[#fbfcf8] px-5 text-sm font-semibold text-[#294634] transition hover:bg-white"><PinIcon /> {item.actions.routeLabel || "Bekijk route"}</a> : null}</div></div></div><ImageSurface image={heroImage} className="relative z-0 min-h-[23rem] overflow-hidden bg-[#cad5c9] sm:min-h-[31rem] lg:min-h-full"><div className="absolute inset-x-0 bottom-0 bg-[linear-gradient(180deg,transparent,rgba(24,39,30,0.6))] p-5 sm:p-7"><p className="text-sm font-medium text-white">{item.practical.venue || item.city}</p></div></ImageSurface></section>
    {item.reasons.length ? <section className="mt-20 sm:mt-28" aria-labelledby="fit-title"><div className="mx-auto max-w-3xl text-center"><p className="inline-flex rounded-full bg-[#eef2e9] px-3 py-1 text-[10px] font-bold uppercase tracking-[0.16em] text-[#315c43]">Waarom dit bij je past</p><h2 id="fit-title" className="mx-auto mt-5 text-[clamp(2.45rem,5vw,4.6rem)] font-semibold leading-[0.93] tracking-[-0.065em] text-[#17291f]">Een uitje dat meer doet dan je agenda vullen.</h2></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{item.reasons.map((reason, index) => <article key={reason} className="rounded-[1.35rem] bg-[#f1f2ed] px-6 py-7 text-center transition hover:-translate-y-1 hover:bg-[#e9eee5]"><span className="mx-auto inline-flex h-10 w-10 items-center justify-center rounded-full bg-[#fbfcf8] text-[#42684f]">{index === 0 ? <SparkIcon /> : <span className="text-sm font-bold">0{index + 1}</span>}</span><p className="mt-5 text-[1.05rem] font-semibold leading-6 tracking-[-0.03em] text-[#203329]">{reason}</p></article>)}</div></section> : null}
    <section className="mt-24 rounded-[1.75rem] bg-[#f1f3eb] px-6 py-9 sm:mt-32 sm:px-10 sm:py-12 lg:px-14 lg:py-16" aria-labelledby="expect-title"><div className="grid gap-10 lg:grid-cols-[minmax(0,0.92fr)_minmax(0,1.08fr)] lg:gap-16"><div><h2 id="expect-title" className="mt-5 text-[clamp(2.3rem,4vw,3.9rem)] font-semibold leading-[0.93] tracking-[-0.06em] text-[#17291f]">Wat kun je verwachten?</h2><p className="mt-6 max-w-xl text-[1rem] leading-8 text-[#5e6d62]">{item.aboutText}</p>{item.description ? <p className="mt-4 max-w-xl text-[1rem] leading-8 text-[#5e6d62]">{item.description}</p> : null}</div><div className="grid gap-3 sm:grid-cols-2"><article className="rounded-[1.15rem] border border-[#dbe1d8] bg-[#fbfcf8] p-6"><span className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#578063]">Categorie</span><p className="mt-3 text-xl font-semibold tracking-[-0.04em]">{item.category}</p></article><article className="rounded-[1.15rem] border border-[#dbe1d8] bg-[#fbfcf8] p-6"><span className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#578063]">Prijs</span><p className="mt-3 text-xl font-semibold tracking-[-0.04em]">{item.practical.pricing || "Op aanvraag"}</p></article><article className="rounded-[1.15rem] border border-[#dbe1d8] bg-[#fbfcf8] p-6 sm:col-span-2"><span className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#578063]">Praktisch</span><p className="mt-3 text-lg font-semibold tracking-[-0.04em]">{item.practical.openingHours || "Controleer de actuele openingstijden"}</p></article></div></div></section>
    <section className="mx-auto mt-24 max-w-[1040px] sm:mt-32" aria-labelledby="visit-title"><h2 id="visit-title" className="mt-3 text-[clamp(2.3rem,4vw,3.7rem)] font-semibold leading-[0.94] tracking-[-0.06em] text-[#17291f]">Plan je bezoek</h2><div className="mt-8 space-y-4"><InfoGroup title="In één oogopslag" rows={practicalRows} /><InfoGroup title="Handig om te weten" rows={visitRows} /></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><a href={reserveHref} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#203d2e] px-5 text-sm font-semibold text-white transition hover:bg-[#315b43]"><TicketIcon /> {item.actions.reserveLabel || "Bekijk opties"}</a>{routeHref ? <a href={routeHref} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-[#c9d3c7] bg-white px-5 text-sm font-semibold text-[#294634] transition hover:bg-[#f2f6ef]"><PinIcon /> Plan route</a> : null}{typeof item.eventId === "number" ? <FavouriteButton eventId={item.eventId} className="inline-flex min-h-12 items-center justify-center rounded-full border border-[#c9d3c7] bg-white px-5 text-sm font-semibold text-[#294634] transition hover:bg-[#f2f6ef]" savedClassName="inline-flex min-h-12 items-center justify-center rounded-full bg-[#e4efe0] px-5 text-sm font-semibold text-[#315c43]" /> : null}</div></section>
    {item.similarPlaces.length ? <section className="mt-24 sm:mt-32" aria-labelledby="similar-title"><h2 id="similar-title" className="mt-3 text-[clamp(2.25rem,4vw,3.6rem)] font-semibold leading-[0.94] tracking-[-0.06em] text-[#17291f]">Misschien ook leuk</h2><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{item.similarPlaces.slice(0, 4).map((place) => <article key={place.title} className="group"><ImageSurface image={place.image} className="aspect-[1.08] overflow-hidden rounded-[1.35rem] bg-[#e1e6dd] transition group-hover:scale-[0.985]"><span className="m-3 inline-flex rounded-full bg-white/88 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-[#315c43]">{place.badge}</span></ImageSurface><h3 className="mt-4 text-[1.12rem] font-semibold leading-tight tracking-[-0.035em] text-[#203329]">{place.title}</h3><p className="mt-2 text-sm font-semibold text-[#345846]">{place.subtitle}</p></article>)}</div></section> : null}
    <section className="mt-24 sm:mt-32" aria-labelledby="gallery-title"><h2 id="gallery-title" className="mt-3 max-w-2xl text-[clamp(2.25rem,4vw,3.6rem)] font-semibold leading-[0.94] tracking-[-0.06em] text-[#17291f]">Een voorproefje van je volgende uitje.</h2><div className="mt-9 grid gap-3 md:grid-cols-12 md:grid-rows-2"><ImageSurface image={item.gallery[0] || heroImage} className="relative min-h-[17rem] overflow-hidden rounded-[1.45rem] bg-[#d9e2d7] md:col-span-5 md:row-span-2 md:min-h-[34.5rem]"><span className="absolute bottom-4 left-4 rounded-full bg-white/90 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.15em] text-[#294634]">Sfeerbeeld</span></ImageSurface><ImageSurface image={item.gallery[1] || heroImage} className="min-h-[15rem] overflow-hidden rounded-[1.45rem] bg-[#e8e3d7] md:col-span-7 md:min-h-0" /><ImageSurface image={item.gallery[2] || heroImage} className="min-h-[15rem] overflow-hidden rounded-[1.45rem] bg-[#dfe7df] md:col-span-3 md:min-h-0" /><ImageSurface image={item.gallery[3] || heroImage} className="min-h-[15rem] overflow-hidden rounded-[1.45rem] bg-[#e8e3d7] md:col-span-4 md:min-h-0" /></div></section>
  </div></main>;
}
