import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { buildGoogleCalendarHref, buildTicketSearchHref } from "@/lib/actionLinks";
import { optimizeCssBackground } from "@/lib/remoteImage";
import { generateFestivalStaticParams, getDiscoverMoreFestivals, getFestivalBySlug, getFestivalDetailHref, type FestivalDetail } from "../data";

type PageProps = { params: { events: string } };

const monthIndexes: Record<string, number> = { january: 0, february: 1, march: 2, april: 3, may: 4, june: 5, july: 6, august: 7, september: 8, october: 9, november: 10, december: 11 };

export const dynamicParams = false;
export function generateStaticParams() { return generateFestivalStaticParams(); }
export function generateMetadata({ params }: PageProps): Metadata {
  const festival = getFestivalBySlug(params.events);
  return festival ? { title: `${festival.name} | Uitjes NL`, description: `${festival.dateLabel} in ${festival.locationLabel}.`, alternates: { canonical: `/festivals/${encodeURIComponent(params.events)}` } } : { title: "Festival | Uitjes NL" };
}

function ArrowLeftIcon() { return <svg className="h-4 w-4" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M12.667 8H3.333M7.333 12 3.333 8l4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function ArrowRightIcon() { return <svg className="h-4 w-4" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M3.333 8h9.334M8.667 3.333 13.333 8l-4.666 4.667" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function CalendarIcon() { return <svg className="h-4 w-4" viewBox="0 0 16 16" fill="none" aria-hidden="true"><rect x="2.5" y="3.5" width="11" height="10" rx="2" stroke="currentColor" strokeWidth="1.4" /><path d="M5 2.5v3M11 2.5v3M2.75 6.25h10.5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" /></svg>; }
function MapPinIcon() { return <svg className="h-4 w-4" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M8 14s4-3.6 4-7.333A4 4 0 1 0 4 6.667C4 10.4 8 14 8 14Z" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" /><circle cx="8" cy="6.667" r="1.4" fill="currentColor" /></svg>; }

function FestivalHero({ festival }: { festival: FestivalDetail }) {
  return <section className="relative isolate overflow-hidden bg-[#fbfaf8] pb-10 pt-24 sm:pb-12 sm:pt-28 lg:pt-28" aria-labelledby="festival-hero-title">
    <div aria-hidden="true" className="absolute inset-0 -z-10" style={{ background: "radial-gradient(ellipse 48% 54% at 18% 68%, rgba(255,221,211,.8), transparent 72%), radial-gradient(ellipse 45% 56% at 53% 78%, rgba(255,243,190,.74), transparent 72%), radial-gradient(ellipse 52% 62% at 86% 79%, rgba(207,235,251,.76), transparent 74%), linear-gradient(180deg,#fbfaf8 0%,#fbfaf7 35%,#f7faf8 100%)" }} />
    <div aria-hidden="true" className="absolute inset-x-0 bottom-0 h-px bg-white/85" />
    <div className="relative mx-auto max-w-[1280px] px-5 sm:px-7 lg:px-8"><Link href="/festivals" className="inline-flex min-h-10 items-center gap-2 rounded-full px-3 text-[13px] font-medium text-[#65625d] transition hover:bg-white/65 hover:text-[#25231f] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#81a84e] sm:absolute sm:left-7 sm:top-0 lg:left-8"><ArrowLeftIcon />Terug naar festivals</Link><div className="mx-auto mt-9 flex max-w-[58rem] flex-col items-center text-center sm:mt-0"><h1 id="festival-hero-title" style={{ fontFamily: "var(--font-body)" }} className="mt-2 max-w-none text-[clamp(3rem,6vw,5.7rem)] font-medium leading-[0.94] tracking-[-0.075em] text-[#171715]">{festival.name}</h1><p className="mt-3 text-sm leading-6 text-[#65635e] sm:text-[15px]">{festival.genres.join(" · ")}</p><div className="mt-7 flex max-w-full flex-wrap justify-center gap-2 sm:mt-8"><span className="inline-flex min-h-10 items-center gap-2 rounded-full border border-black/[0.08] bg-white/72 px-4 text-[13px] font-medium text-[#36342f] shadow-[0_5px_18px_rgba(46,42,36,0.045)]"><CalendarIcon />{festival.dateLabel}</span><span className="inline-flex min-h-10 items-center gap-2 rounded-full border border-black/[0.08] bg-white/72 px-4 text-[13px] font-medium text-[#36342f] shadow-[0_5px_18px_rgba(46,42,36,0.045)]"><MapPinIcon />{festival.locationLabel}</span></div></div></div>
  </section>;
}

function FestivalIntroduction({ festival }: { festival: FestivalDetail }) {
  return <section aria-labelledby="festival-introduction-title"><div className="mx-auto max-w-[42rem] text-center"><h2 id="festival-introduction-title" style={{ fontFamily: "var(--font-body)" }} className="text-[clamp(2rem,4vw,3.05rem)] font-semibold leading-[0.98] tracking-[-0.06em] text-[#181612]">Over {festival.name}</h2></div><div className="mt-9 grid overflow-hidden rounded-[1.65rem] border border-[#e6ded4] bg-[#fffdf9] shadow-[0_18px_48px_rgba(61,40,22,0.045)] lg:grid-cols-[1.15fr_0.85fr]"><div className="min-h-[18rem] bg-[#dfe5dc] sm:min-h-[22rem] lg:min-h-[28rem]" style={{ backgroundImage: `linear-gradient(180deg,rgba(18,24,20,.02),rgba(18,24,20,.18)), ${optimizeCssBackground(festival.heroImage, { width: 1400, quality: 68 })}`, backgroundSize: "cover", backgroundPosition: "center" }} /><div className="flex min-w-0 flex-col items-start px-6 py-7 sm:px-9 sm:py-9 lg:px-10 lg:py-11"><h3 className="max-w-none text-[clamp(2rem,3.4vw,3rem)] leading-[0.96] tracking-[-0.06em] text-[#171511]">{festival.benchmarkPrefix} <span className="text-[#486b37]">{festival.benchmarkHighlight}</span> {festival.benchmarkSuffix}</h3><div className="mt-5 space-y-4 text-[0.98rem] leading-7 text-[#695f55]">{festival.introParagraphs.filter(Boolean).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></div></section>;
}

function SectionHeading({ id, title, detail }: { id: string; title: string; detail?: string }) { return <div className="border-t border-[#e4ddd3] pt-10 sm:pt-12"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><h2 id={id} style={{ fontFamily: "var(--font-body)" }} className="max-w-none text-[clamp(2.15rem,4vw,3.35rem)] font-semibold leading-[0.96] tracking-[-0.065em] text-[#171511]">{title}</h2>{detail ? <p className="pb-1 text-[15px] leading-6 text-[#71675c]">{detail}</p> : null}</div></div>; }
function getFestivalDayDate(dateLabel: string) { const [month, day] = dateLabel.split(" "); return new Date(Date.UTC(2024, monthIndexes[month.toLowerCase()], Number.parseInt(day, 10), 12)); }

export default function FestivalDetailPage({ params }: PageProps) {
  const festival = getFestivalBySlug(params.events);
  if (!festival) notFound();
  const ticketHref = buildTicketSearchHref(festival.name, festival.locationLabel);
  const discoverMore = getDiscoverMoreFestivals(festival.slug);
  return <main className="min-h-screen overflow-x-hidden bg-[#f8f5f3] text-[#171511]"><FestivalHero festival={festival} /><div className="mx-auto max-w-[1280px] px-5 pb-12 pt-10 sm:px-7 lg:px-8 lg:pb-16"><FestivalIntroduction festival={festival} />
    {festival.lineupDays.length ? <section className="mt-16 sm:mt-20" aria-labelledby="lineup-title"><SectionHeading id="lineup-title" title="Programma." detail={`${festival.lineupDays.length} festivaldagen`} /><div className="mt-10 grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3 lg:gap-x-6 lg:gap-y-10">{festival.lineupDays.map((day) => { const start = getFestivalDayDate(day.dateLabel); const calendarHref = buildGoogleCalendarHref({ title: `${festival.name} - ${day.label}`, details: day.acts.map((act) => `${act.name} (${act.genre})`).join(", "), location: festival.locationLabel, start, end: new Date(start.getTime() + 8 * 60 * 60 * 1000) }); return <article key={day.label} className="flex h-full flex-col overflow-hidden rounded-[1.35rem] border border-[#e6ded4] bg-[#fffdf9] px-5 py-6 shadow-[0_12px_34px_rgba(61,40,22,0.035)] sm:px-6"><h3 className="mt-3 text-[clamp(1.45rem,2.1vw,1.85rem)] leading-[0.98] tracking-[-0.05em] text-[#171511]">{day.dateLabel}</h3><div className="mt-5 space-y-4">{day.acts.map((act) => <div key={act.name} className="border-b border-[#e8e1d8] pb-4 last:border-0 last:pb-0"><p className="text-sm font-semibold text-[#403b35]">{act.name}</p><p className="mt-1 text-sm text-[#756c62]">{act.genre}</p></div>)}</div><a href={calendarHref} target="_blank" rel="noreferrer" className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-[#2e5937] transition hover:text-[#173b28] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#83aa50]">Zet in agenda <ArrowRightIcon /></a></article>; })}</div></section> : null}
    {festival.ticketTiers.length ? <section className="mt-16 sm:mt-20" aria-labelledby="tickets-title"><SectionHeading id="tickets-title" title="Plan je bezoek." detail="Tickets en toegang" /><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 lg:gap-4">{festival.ticketTiers.map((tier) => <a key={tier.name} href={ticketHref} target="_blank" rel="noreferrer" className="group flex min-h-[10.25rem] flex-col justify-between rounded-[1.25rem] border border-[#d5dacf] bg-[#f8f8f3]/80 p-5 transition duration-300 hover:-translate-y-0.5 hover:border-[#b8c6aa] hover:bg-[#fbfbf7] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#6d9145] sm:p-6"><span className="text-sm font-semibold text-[#2e4930]">{tier.name}{tier.badge ? <span className="ml-2 rounded-full bg-[#e0edc4] px-2 py-1 text-[10px] uppercase tracking-[0.12em] text-[#385229]">{tier.badge}</span> : null}</span><span className="mt-8"><span className="block text-[1.35rem] font-medium leading-[1.05] tracking-[-0.045em] text-[#252b24]">{tier.priceLabel}</span><span className="mt-3 block text-sm leading-6 text-[#65705f]">{tier.bullets.filter(Boolean).join(" · ")}</span></span></a>)}</div></section> : null}
    {festival.infoCards.length ? <section className="mt-16 sm:mt-20" aria-labelledby="info-title"><SectionHeading id="info-title" title="Praktische informatie." /><div className="mt-10 grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3 lg:gap-x-6 lg:gap-y-10">{festival.infoCards.map((card) => <article key={card.title} className="rounded-[1.35rem] border border-[#e6ded4] bg-[#fffdf9] px-5 py-6 shadow-[0_12px_34px_rgba(61,40,22,0.035)] sm:px-6"><h3 className="text-[clamp(1.45rem,2.1vw,1.85rem)] leading-[0.98] tracking-[-0.05em] text-[#171511]">{card.title}</h3><p className="mt-4 text-sm leading-6 text-[#756c62]">{card.description}</p><p className="mt-6 text-sm font-semibold text-[#2e5937]">{card.cta}</p></article>)}</div></section> : null}
    {discoverMore.length ? <section className="mt-16 sm:mt-20" aria-labelledby="related-title"><SectionHeading id="related-title" title="Meer festivals." detail="Ontdek wat er nog meer speelt" /><div className="mt-10 grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-3 lg:gap-x-6 lg:gap-y-10">{discoverMore.map((item) => <Link key={item.slug} href={getFestivalDetailHref(item.slug)} className="group flex h-full flex-col overflow-hidden rounded-[1.35rem] border border-[#e6ded4] bg-[#fffdf9] shadow-[0_12px_34px_rgba(61,40,22,0.035)] transition duration-300 hover:-translate-y-1 hover:border-[#cfd9c5] hover:shadow-[0_18px_42px_rgba(61,40,22,0.065)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#83aa50]"><div className="aspect-[4/3] bg-[#dfe5dc] transition duration-500 group-hover:scale-[1.025]" style={{ backgroundImage: `linear-gradient(180deg,rgba(21,25,22,.02),rgba(21,25,22,.16)), ${optimizeCssBackground(item.heroImage, { width: 900, quality: 62 })}`, backgroundSize: "cover", backgroundPosition: "center" }} /><div className="flex flex-1 flex-col px-5 py-6 sm:px-6"><h3 className="text-[clamp(1.45rem,2.1vw,1.85rem)] leading-[0.98] tracking-[-0.05em] text-[#171511]">{item.name}</h3><p className="mt-4 text-sm font-medium leading-6 text-[#635b52]">{item.locationLabel} · {item.dateLabel}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#2e5937]">Bekijk festival <ArrowRightIcon /></span></div></Link>)}</div></section> : null}
  </div></main>;
}
