import Link from "next/link";
import { notFound } from "next/navigation";

import Breadcrumbs from "@/components/Breadcrumbs";
import SavePlaceButton from "@/components/SavePlaceButton";
import { buildActionSearchHref, buildMapsSearchHref } from "@/lib/actionLinks";
import { optimizeCssBackground } from "@/lib/remoteImage";
import {
  getInspirationDetailStaticParams,
  getInspirationResultBySlug,
  getSimilarInspirationResults,
  inspirationCategoryLabels,
  isInspirationCategorySlug,
  type InspirationResult,
} from "@/lib/dummy/inspirationResults";

type PageProps = { params: { category: string; slug: string }; searchParams?: { location?: string; nearbyCity?: string } };
export const dynamicParams = false;
export const runtime = "edge";

function buildContextQuery(searchParams?: PageProps["searchParams"]) {
  const params = new URLSearchParams();
  if (searchParams?.location) params.set("location", searchParams.location);
  if (searchParams?.nearbyCity) params.set("nearbyCity", searchParams.nearbyCity);
  return params.toString();
}
function withContext(href: string, query: string) { return query ? `${href}?${query}` : href; }
export function generateStaticParams() { return getInspirationDetailStaticParams(); }
export function generateMetadata({ params }: PageProps) {
  const result = getInspirationResultBySlug(params.category, params.slug);
  return result ? { title: `${result.title} | Uitjes`, description: result.description, alternates: { canonical: `/inspiratie/${params.category}/${params.slug}` } } : { title: "Inspiratie | Uitjes" };
}

function PinIcon() { return <svg className="h-4 w-4" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M8 14s4-3.6 4-7.333A4 4 0 1 0 4 6.667C4 10.4 8 14 8 14Z" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" /><circle cx="8" cy="6.667" r="1.4" fill="currentColor" /></svg>; }
function HeartIcon({ filled = false }: { filled?: boolean }) { return <svg className="h-[18px] w-[18px]" viewBox="0 0 20 20" fill={filled ? "currentColor" : "none"} aria-hidden="true"><path d="M10 17.2S3.25 13.24 3.25 7.86C3.25 5.79 4.84 4.2 6.82 4.2c1.26 0 2.37.63 3.18 1.66.81-1.03 1.92-1.66 3.18-1.66 1.98 0 3.57 1.59 3.57 3.66 0 5.38-6.75 9.34-6.75 9.34Z" stroke="currentColor" strokeWidth="1.45" strokeLinejoin="round" /></svg>; }
function ArrowIcon() { return <svg className="h-4 w-4" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M3.333 8h9.334M8.667 3.333 13.333 8l-4.666 4.667" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function SparkIcon() { return <svg className="h-5 w-5" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m10 2 1.48 5.1L16.5 8.5l-5.02 1.4L10 15l-1.48-5.1L3.5 8.5l5.02-1.4L10 2Z" stroke="currentColor" strokeWidth="1.35" strokeLinejoin="round" /></svg>; }
function ImagePanel({ image, className, children }: { image: string; className: string; children?: React.ReactNode }) { return <div className={className} style={{ backgroundImage: `linear-gradient(180deg, rgba(25,45,33,0.02), rgba(25,45,33,0.24)), ${optimizeCssBackground(image, { width: 1200, quality: 68 })}`, backgroundSize: "cover", backgroundPosition: "center" }}>{children}</div>; }
function SimilarItem({ item, href }: { item: InspirationResult; href: string }) { return <article className="group"><Link href={href} className="block focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#1f5c43]"><ImagePanel image={item.image} className="aspect-[1.08] overflow-hidden rounded-[1.35rem] bg-[#e1e6dd] transition duration-500 group-hover:scale-[0.985]"><span className="m-3 inline-flex rounded-full bg-white/88 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.14em] text-[#315c43]">{item.categoryLabel}</span></ImagePanel></Link><p className="mt-4 text-xs font-medium text-[#74766e]">{item.city}</p><Link href={href} className="mt-1 block text-[1.12rem] font-semibold leading-tight tracking-[-0.035em] text-[#203329] transition group-hover:text-[#1f5c43]">{item.title}</Link><p className="mt-2 text-sm font-semibold text-[#345846]">{item.price}</p></article>; }
function DetailGroup({ title, rows }: { title: string; rows: Array<[string, string]> }) { return <details open className="group overflow-hidden rounded-[1.05rem] border border-[#dce1d9] bg-[#fdfdf9] [&_summary::-webkit-details-marker]:hidden"><summary className="flex min-h-[4.5rem] cursor-pointer list-none items-center justify-between gap-4 px-5 text-[1.02rem] font-semibold tracking-[-0.025em] text-[#25382e]"><span>{title}</span><svg className="h-4 w-4 text-[#59685d] transition group-open:rotate-180" viewBox="0 0 16 16" fill="none"><path d="m4 9.5 4-4 4 4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg></summary><dl className="border-t border-[#e2e5df]">{rows.map(([label, value]) => <div key={label} className="grid gap-1 border-b border-[#e2e5df] px-5 py-3.5 last:border-0 sm:grid-cols-[9rem_1fr] sm:gap-6"><dt className="text-sm text-[#70776f]">{label}</dt><dd className="text-sm font-semibold leading-6 text-[#25382e]">{value}</dd></div>)}</dl></details>; }

export default function InspirationDetailPage({ params, searchParams }: PageProps) {
  if (!isInspirationCategorySlug(params.category)) notFound();
  const activeCategory = params.category;
  const result = getInspirationResultBySlug(params.category, params.slug);
  if (!result) notFound();
  const query = buildContextQuery(searchParams);
  const categoryLabel = inspirationCategoryLabels[activeCategory];
  const detailHref = withContext(`/inspiratie/${params.category}/${params.slug}`, query);
  const savedPlace = { id: `inspiratie:${params.category}/${result.slug}`, title: result.title, href: detailHref, meta: `${result.city} · ${categoryLabel} · ${result.rating}`, image: result.image };
  const similar = getSimilarInspirationResults(result);
  const searchHref = buildActionSearchHref({ title: result.title, location: result.location, actionLabel: "reserveer" });
  const routeHref = buildMapsSearchHref(result.location);
  const practical = [["Locatie", result.location], ["Openingstijden", result.openingHours], ["Prijs", result.price], ["Type", result.type]] as Array<[string, string]>;

  return <main className="min-h-screen bg-[#fbfaf6] text-[#203329]"><div className="mx-auto max-w-[1420px] px-4 pb-20 pt-5 sm:px-6 sm:pt-8 lg:px-10 lg:pb-28">
    <Breadcrumbs className="mb-7 sm:mb-9" items={[{ label: "Inspiratie", href: "/inspiratie" }, { label: categoryLabel, href: withContext(`/inspiratie/${params.category}`, query) }, { label: result.title }]} />
    <section className="overflow-hidden rounded-[1.75rem] bg-[#eff0eb] shadow-[0_24px_70px_rgba(33,49,40,0.08)] lg:grid lg:grid-cols-[minmax(0,0.88fr)_minmax(0,1.12fr)]" aria-labelledby="inspiration-title"><div className="relative z-10 min-w-0 overflow-hidden px-6 py-8 sm:px-10 sm:py-11 lg:px-14 lg:py-14"><div className="absolute left-0 top-0 h-24 w-24 rounded-br-[5rem] border-b border-r border-[#dae4d7]" aria-hidden="true" /><div className="relative"><div className="flex items-center justify-between gap-3"><span className="inline-flex rounded-full bg-[#e4efe0] px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.17em] text-[#315c43]">{result.type || categoryLabel}</span><SavePlaceButton item={savedPlace} className="inline-flex h-11 w-11 items-center justify-center rounded-full border border-[#d8dfd6] bg-[#fbfcf8] text-[#345846] transition hover:border-[#345846] hover:bg-white" savedClassName="inline-flex h-11 w-11 items-center justify-center rounded-full bg-[#345846] text-white" savedChildren={<><HeartIcon filled /><span className="sr-only">Verwijder uit bewaard</span></>}><HeartIcon /><span className="sr-only">Bewaar dit uitje</span></SavePlaceButton></div><h1 id="inspiration-title" className="mt-8 max-w-[10ch] break-words text-[clamp(3.25rem,6.2vw,6.4rem)] font-semibold leading-[0.88] tracking-[-0.072em] text-[#15251d] [overflow-wrap:anywhere]">{result.title}</h1><p className="mt-6 max-w-xl text-[1rem] leading-7 text-[#5f6d63] sm:text-[1.08rem]">{result.description}</p><div className="mt-7 flex flex-wrap gap-2">{result.tags.map((tag) => <span key={tag} className="rounded-full border border-[#d4dfd1] bg-[#f8fbf5] px-3 py-1.5 text-xs font-semibold text-[#41644c]">{tag}</span>)}</div><div className="mt-8 flex flex-wrap gap-3"><a href={searchHref} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#203d2e] px-5 text-sm font-semibold text-white transition hover:bg-[#315b43]">Zoek actuele informatie <ArrowIcon /></a><a href={routeHref} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-[#c8d3c7] bg-[#fbfcf8] px-5 text-sm font-semibold text-[#294634] transition hover:bg-white"><PinIcon /> Bekijk route</a></div></div></div><ImagePanel image={result.image} className="relative z-0 min-h-[23rem] overflow-hidden bg-[#cad5c9] sm:min-h-[31rem] lg:min-h-full"><div className="absolute inset-x-0 bottom-0 bg-[linear-gradient(180deg,transparent,rgba(24,39,30,0.6))] p-5 sm:p-7"><p className="text-sm font-medium text-white">{result.location} · {result.city}</p></div></ImagePanel></section>
    <section className="mt-20 sm:mt-28" aria-labelledby="fit-title"><div className="mx-auto max-w-3xl text-center"><p className="inline-flex rounded-full bg-[#eef2e9] px-3 py-1 text-[10px] font-bold uppercase tracking-[0.16em] text-[#315c43]">Waarom dit bij je past</p><h2 id="fit-title" className="mx-auto mt-5 text-[clamp(2.45rem,5vw,4.6rem)] font-semibold leading-[0.93] tracking-[-0.065em] text-[#17291f]">Een tip die past bij jouw vrije moment.</h2></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{result.reasons.map((reason, index) => <article key={reason} className="rounded-[1.35rem] bg-[#f1f2ed] px-6 py-7 text-center transition hover:-translate-y-1 hover:bg-[#e9eee5]"><span className="mx-auto inline-flex h-10 w-10 items-center justify-center rounded-full bg-[#fbfcf8] text-[#42684f]">{index === 0 ? <SparkIcon /> : index === 1 ? <PinIcon /> : <span className="text-sm font-bold">0{index + 1}</span>}</span><p className="mt-5 text-[1.05rem] font-semibold leading-6 tracking-[-0.03em] text-[#203329]">{reason}</p></article>)}</div></section>
    <section className="mt-24 rounded-[1.75rem] bg-[#f1f3eb] px-6 py-9 sm:mt-32 sm:px-10 sm:py-12 lg:px-14 lg:py-16" aria-labelledby="expect-title"><div className="grid gap-10 lg:grid-cols-[minmax(0,0.92fr)_minmax(0,1.08fr)] lg:gap-16"><div><h2 id="expect-title" className="mt-5 text-[clamp(2.3rem,4vw,3.9rem)] font-semibold leading-[0.93] tracking-[-0.06em] text-[#17291f]">Wat kun je verwachten?</h2><p className="mt-6 max-w-xl text-[1rem] leading-8 text-[#5e6d62]">{result.description}</p><p className="mt-4 max-w-xl text-[1rem] leading-8 text-[#5e6d62]">{result.practicalInfo}</p></div><div className="grid gap-3 sm:grid-cols-2"><article className="rounded-[1.15rem] border border-[#dbe1d8] bg-[#fbfcf8] p-6"><span className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#578063]">Type</span><p className="mt-3 text-xl font-semibold tracking-[-0.04em]">{result.type}</p></article><article className="rounded-[1.15rem] border border-[#dbe1d8] bg-[#fbfcf8] p-6"><span className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#578063]">Prijs</span><p className="mt-3 text-xl font-semibold tracking-[-0.04em]">{result.price}</p></article><article className="rounded-[1.15rem] border border-[#dbe1d8] bg-[#fbfcf8] p-6 sm:col-span-2"><span className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#578063]">Waardering</span><p className="mt-3 text-xl font-semibold tracking-[-0.04em]">{result.rating} / 5</p></article></div></div></section>
    <section className="mx-auto mt-24 max-w-[1040px] sm:mt-32" aria-labelledby="visit-title"><h2 id="visit-title" className="mt-3 text-[clamp(2.3rem,4vw,3.7rem)] font-semibold leading-[0.94] tracking-[-0.06em] text-[#17291f]">Plan je bezoek</h2><div className="mt-8 space-y-4"><DetailGroup title="In één oogopslag" rows={practical} /><DetailGroup title="Handig om te weten" rows={[["Praktisch", result.practicalInfo], ["Tags", result.tags.join(" · ")]]} /></div></section>
    {similar.length ? <section className="mt-24 sm:mt-32" aria-labelledby="similar-title"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 id="similar-title" className="mt-3 text-[clamp(2.25rem,4vw,3.6rem)] font-semibold leading-[0.94] tracking-[-0.06em] text-[#17291f]">Misschien ook leuk</h2></div><Link href={withContext(`/inspiratie/${activeCategory}`, query)} className="inline-flex items-center gap-2 text-sm font-semibold text-[#315c43]">Bekijk alles <ArrowIcon /></Link></div><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{similar.map((item) => <SimilarItem key={item.slug} item={item} href={withContext(`/inspiratie/${item.categories.includes(activeCategory) ? activeCategory : item.category}/${item.slug}`, query)} />)}</div></section> : null}
    <section className="mt-24 sm:mt-32" aria-labelledby="gallery-title"><h2 id="gallery-title" className="mt-3 max-w-2xl text-[clamp(2.25rem,4vw,3.6rem)] font-semibold leading-[0.94] tracking-[-0.06em] text-[#17291f]">Een voorproefje van je volgende uitje.</h2><div className="mt-9 grid gap-3 md:grid-cols-12 md:grid-rows-2"><ImagePanel image={result.gallery[0] || result.image} className="relative min-h-[17rem] overflow-hidden rounded-[1.45rem] bg-[#d9e2d7] md:col-span-5 md:row-span-2 md:min-h-[34.5rem]"><span className="absolute bottom-4 left-4 rounded-full bg-white/90 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.15em] text-[#294634]">Sfeerbeeld</span></ImagePanel><ImagePanel image={result.gallery[1] || result.image} className="min-h-[15rem] overflow-hidden rounded-[1.45rem] bg-[#e8e3d7] md:col-span-7 md:min-h-0" /><ImagePanel image={result.gallery[2] || result.image} className="min-h-[15rem] overflow-hidden rounded-[1.45rem] bg-[#dfe7df] md:col-span-3 md:min-h-0" /><ImagePanel image={result.gallery[3] || result.image} className="min-h-[15rem] overflow-hidden rounded-[1.45rem] bg-[#e8e3d7] md:col-span-4 md:min-h-0" /></div></section>
  </div></main>;
}
